services:
  backrest-listener-db:
    image: postgres:17
    container_name: backrest-listener-db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: backrest-listener-db
    volumes:
      - backrest-listener-db-data:/var/lib/postgresql/data
    ports:
      - "57432:5432"

  backrest-listener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backrest-listener
    depends_on:
      - backrest-listener-db
    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@backrest-listener-db/backrest-listener-db
      TZ: America/New_York
      AUTH_KEY: ${AUTH_KEY}
      RUST_LOG: info
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_TO: ${EMAIL_TO}
    ports:
      - "2682:2682"

# TODO: - Move this to a normal directory so that we can back it up
volumes:
  backrest-listener-db-data:
